# Jekyll
permalink: pretty
paginate: 10 
name: OpenStack4j
baseurl: 
markdown: kramdown
version: 1.0.1
snapshot-version: 1.0.2-SNAPSHOT
withdeps-version: 1.0.2-withdeps
url: http://www.openstack4j.com
