# Jekyll
permalink: pretty
paginate: 10 
name: OpenStack4j
baseurl: 
markdown: kramdown
version: 2.0.0
snapshot-version: 2.0.1-SNAPSHOT
withdeps-version: 2.0.1-withdeps
url: http://www.openstack4j.com
