# Jekyll
permalink: pretty
paginate: 10 
name: OpenStack4j
baseurl: 
markdown: kramdown
version: 1.0.2
snapshot-version: 1.0.3-SNAPSHOT
withdeps-version: 1.0.3-withdeps
url: http://www.openstack4j.com
